In [3]:
import pandas as pd
from pathlib import Path

## Ingestao dos dados

In [ ]:
data_source = Path(r"C:\Users\dougl\OneDrive\Área de Trabalho\POS\pratica do que aprendi\modulo01-fundamentos-de-ia-e-llms-para-programadores\exemplo-01\Redes Neurais\data\Bank_churn.csv")

In [6]:
data_source.exists()

True

In [14]:
df = pd.read_csv(data_source)

## Exploracao dos dados

In [15]:
df.head()

,id,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Rating,Exited,"Geography:str,Gender:str"
0,0.0,15674932.0,"O,k{wudilic_-huk>wu_",668.0,33.0,3.0,0.00,2.0,1.0,0.0,181449.97,-3,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
1,1.0,15749177.0,"O{kwudi""li#%%'oli=-sa",627.0,33.0,1.0,0.00,2.0,1.0,1.0,49503.5,0,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
2,2.0,15694510.0,Hsueh,678.0,40.0,10.0,0.00,2.0,1.0,0.0,184866.69,1,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
3,3.0,15741417.0,"Kao,]?>?%]@",581.0,34.0,2.0,148882.54,1.0,1.0,1.0,84560.88,-4,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
4,4.0,15766172.0,Ch-i]emen'-am,716.0,33.0,5.0,0.00,2.0,1.0,1.0,15068.83,-1,0,"{'Geography': 'Madrid-Spain','Gender': 'Male'}"

In [22]:
df.columns

Index(['id', 'CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Rating', 'Exited', 'Geography:str,Gender:str'],
      dtype='str')

In [24]:
df["Geography:str,Gender:str"].head(10)

0      {'Geography': 'Paris-France','Gender': 'Male'}
1      {'Geography': 'Paris-France','Gender': 'Male'}
2      {'Geography': 'Paris-France','Gender': 'Male'}
3      {'Geography': 'Paris-France','Gender': 'Male'}
4      {'Geography': 'Madrid-Spain','Gender': 'Male'}
5     {'Geography': 'Berlin-Gernay','Gender': 'Male'}
6    {'Geography': 'Paris-France','Gender': 'Female'}
7      {'Geography': 'Madrid-Spain','Gender': 'Male'}
8      {'Geography': 'Paris-France','Gender': 'Male'}
9     {'Geography': 'Berlin-Gernay','Gender': 'Male'}
Name: Geography:str,Gender:str, dtype: str

In [25]:
df["Exited"].value_counts()

Exited
0    130113
1     34921
Name: count, dtype: int64

In [26]:
df["Rating"].value_counts()

Rating
-4    16779
 2    16683
 0    16577
-3    16528
-2    16449
 1    16435
 3    16420
 4    16405
-5    16380
-1    16378
Name: count, dtype: int64

In [29]:
df.isnull().sum()

id                          7186
CustomerId                  7526
Surname                     3917
CreditScore                  370
Age                         5599
Tenure                      4707
Balance                     4041
NumOfProducts               5521
HasCrCard                   2843
IsActiveMember              3525
EstimatedSalary             4377
Rating                         0
Exited                         0
Geography:str,Gender:str       0
dtype: int64

In [30]:
df["Geography:str,Gender:str"].value_counts()

Geography:str,Gender:str
{'Geography': 'Paris-France','Gender': 'Male'}       51226
{'Geography': 'Paris-France','Gender': 'Female'}     37819
{'Geography': 'Madrid-Spain','Gender': 'Male'}       19605
{'Geography': 'Berlin-Gernay','Gender': 'Male'}      17265
{'Geography': 'Berlin-Gernay','Gender': 'Female'}    15505
{'Geography': 'Madrid-Spain','Gender': 'Female'}     14684
{'Geography': 'Paris-France','Gender': 'nan'}         4733
{'Geography': 'Madrid-Spain','Gender': 'nan'}         1761
{'Geography': 'Berlin-Gernay','Gender': 'nan'}        1691
{'Geography': 'nan','Gender': 'Male'}                  401
{'Geography': 'nan','Gender': 'Female'}                314
{'Geography': 'nan','Gender': 'nan'}                    30
Name: count, dtype: int64

In [31]:
df["Age"].describe()

count     159435
unique       500
top         38.0
freq        8897
Name: Age, dtype: object

In [32]:
df["EstimatedSalary"].describe()

count       160657
unique       54398
top       88890.05
freq           174
Name: EstimatedSalary, dtype: object

In [33]:
df["Age"].head(20).tolist()

['33.0',
 '33.0',
 '40.0',
 '34.0',
 '33.0',
 '36.0',
 '30.0',
 '37.0',
 '43.0',
 '40.0',
 '27.0',
 nan,
 '71.0',
 '47.0',
 '33.0',
 '25.0',
 '36.0',
 '36.0',
 '55.0',
 '61.0']

In [34]:
df["EstimatedSalary"].head(20).tolist()

['181449.97',
 '49503.5',
 '184866.69',
 '84560.88',
 '15068.83',
 '136024.31',
 '29792.11',
 '106851.6',
 '142917.13',
 '170843.07',
 '109184.24',
 nan,
 '93081.87',
 '72945.68',
 '79997.14',
 '162260.93',
 '135082.47',
 '111573.3',
 '125083.29',
 '180890.4']

In [35]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["EstimatedSalary"] = pd.to_numeric(df["EstimatedSalary"], errors="coerce")

In [36]:
df[["Age", "EstimatedSalary"]].dtypes

Age                float64
EstimatedSalary    float64
dtype: object

In [37]:
df.isnull().sum()

id                          7186
CustomerId                  7526
Surname                     3917
CreditScore                  370
Age                         6108
Tenure                      4707
Balance                     4041
NumOfProducts               5521
HasCrCard                   2843
IsActiveMember              3525
EstimatedSalary             4577
Rating                         0
Exited                         0
Geography:str,Gender:str       0
dtype: int64

## Aqui comecamos a criar os dataframes de tranformacao

In [41]:
df_model = df[
    [
        "CreditScore",
        "Age",
        "Tenure",
        "Balance",
        "NumOfProducts",
        "HasCrCard",
        "IsActiveMember",
        "EstimatedSalary",
        "Geography:str,Gender:str",
        "Exited"
    ]
].copy()

In [42]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CreditScore               164664 non-null  float64
 1   Age                       158926 non-null  float64
 2   Tenure                    160327 non-null  float64
 3   Balance                   160993 non-null  float64
 4   NumOfProducts             159513 non-null  float64
 5   HasCrCard                 162191 non-null  float64
 6   IsActiveMember            161509 non-null  float64
 7   EstimatedSalary           160457 non-null  float64
 8   Geography:str,Gender:str  165034 non-null  str
 9   Exited                    165034 non-null  int64
dtypes: float64(8), int64(1), str(1)
memory usage: 12.6 MB

In [43]:
df_model.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,"Geography:str,Gender:str",Exited
0,668.0,33.0,3.0,0.00,2.0,1.0,0.0,181449.97,"{'Geography': 'Paris-France','Gender': 'Male'}",0
1,627.0,33.0,1.0,0.00,2.0,1.0,1.0,49503.50,"{'Geography': 'Paris-France','Gender': 'Male'}",0
2,678.0,40.0,10.0,0.00,2.0,1.0,0.0,184866.69,"{'Geography': 'Paris-France','Gender': 'Male'}",0
3,581.0,34.0,2.0,148882.54,1.0,1.0,1.0,84560.88,"{'Geography': 'Paris-France','Gender': 'Male'}",0
4,716.0,33.0,5.0,0.00,2.0,1.0,1.0,15068.83,"{'Geography': 'Madrid-Spain','Gender': 'Male'}",0

In [16]:
x = df.drop(columns="Exited")
y = df["Exited"]

In [19]:
x.head()

,id,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Rating,"Geography:str,Gender:str"
0,0.0,15674932.0,"O,k{wudilic_-huk>wu_",668.0,33.0,3.0,0.00,2.0,1.0,0.0,181449.97,-3,"{'Geography': 'Paris-France','Gender': 'Male'}"
1,1.0,15749177.0,"O{kwudi""li#%%'oli=-sa",627.0,33.0,1.0,0.00,2.0,1.0,1.0,49503.5,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
2,2.0,15694510.0,Hsueh,678.0,40.0,10.0,0.00,2.0,1.0,0.0,184866.69,1,"{'Geography': 'Paris-France','Gender': 'Male'}"
3,3.0,15741417.0,"Kao,]?>?%]@",581.0,34.0,2.0,148882.54,1.0,1.0,1.0,84560.88,-4,"{'Geography': 'Paris-France','Gender': 'Male'}"
4,4.0,15766172.0,Ch-i]emen'-am,716.0,33.0,5.0,0.00,2.0,1.0,1.0,15068.83,-1,"{'Geography': 'Madrid-Spain','Gender': 'Male'}"

In [20]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Exited, dtype: int64

In [21]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        157848 non-null  float64
 1   CustomerId                157508 non-null  float64
 2   Surname                   161117 non-null  str
 3   CreditScore               164664 non-null  float64
 4   Age                       159435 non-null  str
 5   Tenure                    160327 non-null  float64
 6   Balance                   160993 non-null  float64
 7   NumOfProducts             159513 non-null  float64
 8   HasCrCard                 162191 non-null  float64
 9   IsActiveMember            161509 non-null  float64
 10  EstimatedSalary           160657 non-null  str
 11  Rating                    165034 non-null  int64
 12  Geography:str,Gender:str  165034 non-null  str
dtypes: float64(8), int64(1), str(4)
memory usage: 16.4 MB